SINGAPORE_ADDRESSES = [
  "Orchard Road, Singapore",
  "Jurong West Street, Singapore",
  "Bukit Timah Road, Singapore",
  "Chinatown Point, Singapore",
  "Serangoon Avenue, Singapore",
  "Woodlands Drive, Singapore",
  "Marina Bay Sands, Bayfront Ave, Singapore",
  "East Coast Road, Singapore",
  "Tampines Central, Singapore",
  "Ang Mo Kio Avenue, Singapore",
  "Clementi Road, Singapore",
  "Raffles Place, Singapore",
  "Bedok Reservoir Road, Singapore",
  "Holland Avenue, Singapore",
  "Simei Street, Singapore",
  "Changi Business Park, Changi South Ave, Singapore",
  "Geylang Road, Singapore",
  "Toa Payoh West, Singapore",
  "North Bridge Road, Singapore",
  "Boon Lay Way, Singapore",
  "Yishun Ring Road, Singapore",
  "Kim Tian Road, Singapore",
  "Sengkang East Avenue, Singapore",
  "Thomson Road, Singapore",
  "Bukit Batok Street, Singapore",
  "Pasir Panjang Road, Singapore",
  "Balestier Road, Singapore",
  "Jalan Besar, Singapore",
  "Tiong Bahru Road, Singapore",
  "Upper Serangoon Road, Singapore"
]

# You now have an array containing modified street addresses with block numbers removed and ", Singapore" added at the end.
